### ISSUE TITLE
コラム内脚注本文の移動

### ISSUE THREAD

**Issue by kmuto** [mochikoAsTech/startDNS#21]
c1f36d737e8dad7bc39b243f79a22169a503efc6 でのビルドで

```
./domain.tex:647: LaTeX Error: Counter too large. ←これがエラー

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.647 ...otetext[28]{\url{https://radix.website/}}
```

## エラー理由
columnブロック内に//footnoteを入れてしまうと、

- Re:VIEW2では何も考えていなかったので//footnoteをコラムの中に入れるとコラム単位で脚注がa,b,cの振り直しでつき、コラムの外に置くと脚注が「消える」という極めてわかりにくい挙動になる。Re:VIEW3では、column脚注を普通の脚注にするためにちょっと内部で特殊なことをして本文採番と合わせるようにしている(footnotemark+footnotetext)。
- ただし、//footnoteをコラムの中に入れるとa,b,c...というカウントになるが、本文採番に基づくのでおかしなことになる。
- 今回の場合、本文も合わせて …、27、28とカウントしてきて、ここはコラム内なのでabc採番で「28」を表現しようとして、zを超えてしまってcounter too largeエラーになる。

## 対処
脚注本体である `//footnote` はコラムの終わりの後ろに置く。

**Comment by kmuto** [comment]
[domain.zip](https://github.com/mochikoAsTech/startDNS/files/3530672/domain.zip)

domain.reをとりあえず直してみた例。

- columnの外に//footnoteを移動。
- gTldというfnが2つあって脚注番号が狂うので、とりあえず2つめのほうをgTld2に変更。

**Comment by mochikoAsTech** [comment]
お陰さまで、アドバイス通りコラム内のfootnoteを外に出すことで解消しました。
エラー理由も丁寧に書いてくださったお陰で分かりやすかったです！

ありがとうございました。

**Comment by kmuto** [comment]
Re:VIEW側で//footnoteをcolumnの中に置いたら毎回リセットでaから始める、外だったら本文採番継続、とかできるといいんでしょうけど、その解析は現状の実装だと困難極まるですね…。
