### ISSUE TITLE
1.9.2 <トラブル>ドメイン自動更新の落とし穴の結論について

### ISSUE THREAD

**Issue by tmatsuba** [mochikoAsTech/startDNS#25]
自動更新自体をOFFにすることで解決する内容ではなく、お知らせ先のメールアドレスを個人の連絡先にしていたことが問題の原因であると思います。

自動更新したことで忘れられた存在となったのは確かですが。

**Comment by mochikoAsTech** [comment]
```
いかがでしたか？想像しただけで怖いですよね。こんなトラブルを起こさないためにも、ドメイン名の自動更新をオンにするときは慎重に！そして更新のお知らせが届く連絡先のアドレスは個人のメールアドレスではなく、チームのメールアドレスなどにしておきましょう。
```
としてみました。

連絡先についての詳細は、直後に続く「=== 【ドリル】連絡先メールアドレスは自分だけでいい？」で解説してるので省略します。
