### ISSUE TITLE
「ドメイン名紛争処理方針」の表記について

### ISSUE THREAD

**Issue by tmatsuba** [mochikoAsTech/startDNS#26]
ドメイン 名紛争処理方針(DRP)* と、括弧書きで略称を書いてあったほうが読みやすいのかなと思いました。
脚注を読む前に次の行でDRPって出てきて、詰まったので。

**Comment by mochikoAsTech** [comment]
`ドメイン名紛争処理方針（DRP）* という仕組みでも対応が可能です。`
としました。
