### ISSUE TITLE
1.8 「ドメイン」なのか「ドメイン名」なのか? の exampleの箇所数とか図とか

### ISSUE THREAD

**Issue by tmatsuba** [mochikoAsTech/startDNS#27]
正式な図ではないので勘違いだったらすいません。

誤：次の図(図 1.15)のように example(2 箇所にある) 
正：次の図(図 1.15)のように example(3 箇所にある)

あと図 1.15と図 1.16は逆？

**Comment by mochikoAsTech** [comment]
ホンマヤン。
直します。

**Comment by mochikoAsTech** [comment]
example3箇所だったので原稿も図も直しましたー。
図 1.15と図 1.16も逆だったので直しました。
