### ISSUE TITLE
1.12.2 ドメイン名の有効期限

### ISSUE THREAD

**Issue by tmatsuba** [mochikoAsTech/startDNS#30]
"丸一年経ってもうすぐ切れてしまいます。"とあって、丸一年経ったらもう切れちゃってる気がしましたが、jpドメインの場合は契約月末日までが契約期間になるんですね。その辺も記載があると良いかと思いました。

**Comment by mochikoAsTech** [comment]
あ、そこまでの深い意図はなかった。＞JPドメイン名の場合

なので `1年弱経って` としました。
