### ISSUE TITLE
脚注番号のバグ

### ISSUE THREAD

**Issue by tmatsuba** [mochikoAsTech/startDNS#31]
PDFの出力ソフトがバグってるのかも？ o, p, qになってます。

```
o https://mochikoastech.booth.pm/
p イラストを投稿できる SNS、pixiv でお馴染み。https://www.pixiv.net/ 
q https://booth.pm/ja/search/技術書典
```

**Comment by mochikoAsTech** [comment]
あーーー。注釈をコラムブロックの中に入れちゃうと、採番がabcになっちゃうのです。
https://mochikoastech.hatenablog.com/entry/2019/08/23/222523

直しましたー。
