### ISSUE TITLE
お名前のドメイン移管について

### ISSUE THREAD

**Issue by tmatsuba** [mochikoAsTech/startDNS#32]
余裕があればの改善提案です。

5.3
お名前のドメイン移管時はネームサーバーの設定も自動で移管される事も記載した方が良いと思いました。
その後の説明としても移管元の設定が残っている前提を書いてあった方がしっくりくるかなと。

**Comment by mochikoAsTech** [comment]
`「お名前ID付け替え」を行うと、ネームサーバやリソースレコードの設定もそのままA社のお名前IDからB社のお名前IDへ引き継がれます。` を足しました。
