### ISSUE TITLE
「 . (ドット)」でつないで一意に識別する文字列はラベル

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startDNS#33]
「ドメイン」なのか「ドメイン名」なのか？ 中の
【「 . (ドット)」でつないで一意に識別する】ための文字列はラベルです。

関連する文献は下記:
 - JPRSのDNSがよくわかる教科書の「ドメイン名の構成」
 - RFC8499を【Domain name:  An ordered list of one or more labels】で検索した周辺

**Comment by mochikoAsTech** [comment]
次のように修正しました。
```
www.example.co.jp というドメイン名の場合、www とexample とco とjp というそれぞれの文字列は「ラベル」と呼ばれ、ドメイン名はこのラベルを「.（ドット）」でつなぐ形で構成されています。
```
