### ISSUE TITLE
CAPTCHAは全部大文字

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startDNS#34]
Captchaがカーネギーメロン大学の登録商標であるところのCAPTCHAを指すのならば、商標的には全部大文字が正しかったはずです。
ソースでなく例示しか出せませんが、http://www.captcha.net/ で。

図に「セキュリティチェック」とあるものをCAPTCHAに言い換えていいのかということには触れません

**Comment by mochikoAsTech** [comment]
ありがとうございます！
`電話番号とセキュリティチェックを入力したら` にしちゃいました。
