### ISSUE TITLE
example.comとexample.netにはAレコード有

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startDNS#35]
例示やテスト専用のドメイン名を使おう 中の【リソースレコードはMXレコードもAレコードも設定されていないため】について。
example.comとexample.netにはAレコードがあります。
(第三者へメールが飛ぶ心配がないことには変わりありませんが)

**Comment by mochikoAsTech** [comment]
本当だ！！！！知らなかった！！！！

https://tools.ietf.org/html/rfc6761#section-5.7
なるほど。。

`リソースレコードはMXレコードもAレコードも設定されていないため、` を削ろうと思います。
ありがとうございます！

```
$ dig example.com a +short
93.184.216.34
$ dig example.net a +short
93.184.216.34
$ dig www.example.net a +short
93.184.216.34
$ dig www.example.net a +short
93.184.216.34
```
