### ISSUE TITLE
図1.9と図1.11中のゴンベエドメインがゴンベイ

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startDNS#37]
本文・ https://www.gonbei.jp/ ではゴンベエドメインですが、図中ではゴンベイになっています。もし同じものを指すとしたら表記が揺れています。

**Comment by mochikoAsTech** [comment]
同じものを指してます！

全然気付いてなかった…ありがとうございます。
図の方が誤りなので、修正しました。
