### ISSUE TITLE
図1.32 ドメインNavi更新アラート の図と本文との文言不一致

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startDNS#39]
どちらが onamae.com の挙動と一致しているかはわかりませんが、図1.32 ドメインNavi更新アラートの図と本文が不一致です。

図: 「このページから移動しますか? 入力したデータは保存されません」
本文: 「このサイトを離れますか? 行った変更が保存されない可能性があります。」

**Comment by mochikoAsTech** [comment]
図が正で、本文が誤りです！
図の差し替えを行った際に、本文側の修正がもれていました。
ありがとうございます。
