### ISSUE TITLE
電話番号例に伏せ字でない箇所

### ISSUE THREAD

**Issue by kaoru6** [mochikoAsTech/startDNS#40]
AWSアカウント作成時に【（例：090-1234-5678）】という記述があります。
他の箇所では【090-〇〇〇〇-〇〇〇〇】のように伏せ字でした。

実在する電話番号かはわかりませんが、もし実在するならば【実在する他人の住所や電話番号を勝手に使わないのと同じように、他人のドメイン名も勝手に使わないようにしましょう】という記述の説得力が薄れます。

**Comment by mochikoAsTech** [comment]
ごもっともです＞＜
伏せ字の方に表記を統一しました。
